import { supabase } from './supabase';
import { logger } from '../utils/logger';
import type { MiraMealPlan, MiraDayPlan, MiraMeal } from './mira';

// Database types
export interface MealPlan {
  id: string;
  household_id: string;
  name: string;
  start_date: string;
  end_date: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface PlannedMeal {
  id: string;
  meal_plan_id: string;
  date: string;
  meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'dessert' | 'other';
  name: string;
  description: string | null;
  calories: number | null;
  prep_time: string | null;
  ingredients: string[];
  instructions: string[];
  is_completed: boolean;
  completed_at: string | null;
  created_at: string;
}

export interface MealPlanWithMeals extends MealPlan {
  planned_meals: PlannedMeal[];
}

// Get all meal plans for a household
export async function getMealPlans(householdId: string): Promise<MealPlanWithMeals[]> {
  try {
    const { data, error } = await supabase
      .from('meal_plans')
      .select(`
        *,
        planned_meals (*)
      `)
      .eq('household_id', householdId)
      .order('start_date', { ascending: false });

    if (error) {
      logger.error('Failed to fetch meal plans:', error);
      throw error;
    }

    return data || [];
  } catch (error) {
    logger.error('getMealPlans error:', error);
    throw error;
  }
}

// Get a single meal plan by ID
export async function getMealPlan(planId: string): Promise<MealPlanWithMeals | null> {
  try {
    const { data, error } = await supabase
      .from('meal_plans')
      .select(`
        *,
        planned_meals (*)
      `)
      .eq('id', planId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null; // Not found
      logger.error('Failed to fetch meal plan:', error);
      throw error;
    }

    return data;
  } catch (error) {
    logger.error('getMealPlan error:', error);
    throw error;
  }
}

// Get meal plans for a specific date range (for calendar integration)
export async function getMealPlansForDateRange(
  householdId: string,
  startDate: Date,
  endDate: Date
): Promise<PlannedMeal[]> {
  try {
    const startStr = startDate.toISOString().split('T')[0];
    const endStr = endDate.toISOString().split('T')[0];

    const { data, error } = await supabase
      .from('planned_meals')
      .select(`
        *,
        meal_plans!inner (
          household_id
        )
      `)
      .eq('meal_plans.household_id', householdId)
      .gte('date', startStr)
      .lte('date', endStr)
      .order('date', { ascending: true });

    if (error) {
      logger.error('Failed to fetch meals for date range:', error);
      throw error;
    }

    return data || [];
  } catch (error) {
    logger.error('getMealPlansForDateRange error:', error);
    throw error;
  }
}

// Get meals for a specific date
export async function getMealsForDate(
  householdId: string,
  date: Date
): Promise<PlannedMeal[]> {
  try {
    const dateStr = date.toISOString().split('T')[0];

    const { data, error } = await supabase
      .from('planned_meals')
      .select(`
        *,
        meal_plans!inner (
          household_id
        )
      `)
      .eq('meal_plans.household_id', householdId)
      .eq('date', dateStr)
      .order('meal_type', { ascending: true });

    if (error) {
      logger.error('Failed to fetch meals for date:', error);
      throw error;
    }

    return data || [];
  } catch (error) {
    logger.error('getMealsForDate error:', error);
    throw error;
  }
}

// Save a meal plan generated by Mira
export async function saveMiraMealPlan(
  householdId: string,
  miraPlan: MiraMealPlan,
  userId?: string
): Promise<MealPlanWithMeals> {
  try {
    // Calculate start and end dates
    const today = new Date();
    const startDate = today.toISOString().split('T')[0];
    const endDate = new Date(today);
    endDate.setDate(today.getDate() + miraPlan.duration - 1);
    const endDateStr = endDate.toISOString().split('T')[0];

    // Create the meal plan
    const { data: mealPlan, error: planError } = await supabase
      .from('meal_plans')
      .insert({
        household_id: householdId,
        name: miraPlan.name || 'Weekly Meal Plan',
        start_date: startDate,
        end_date: endDateStr,
        created_by: userId || null,
      })
      .select()
      .single();

    if (planError) {
      logger.error('Failed to create meal plan:', planError);
      throw planError;
    }

    // Convert Mira's day plans to planned meals
    const plannedMeals: Omit<PlannedMeal, 'id' | 'created_at'>[] = [];

    for (const dayPlan of miraPlan.days) {
      const mealDate = new Date(today);
      mealDate.setDate(today.getDate() + dayPlan.day - 1);
      const dateStr = mealDate.toISOString().split('T')[0];

      // Add breakfast
      if (dayPlan.meals.breakfast) {
        plannedMeals.push(convertMiraMealToPlanned(
          mealPlan.id,
          dateStr,
          'breakfast',
          dayPlan.meals.breakfast
        ));
      }

      // Add lunch
      if (dayPlan.meals.lunch) {
        plannedMeals.push(convertMiraMealToPlanned(
          mealPlan.id,
          dateStr,
          'lunch',
          dayPlan.meals.lunch
        ));
      }

      // Add dinner
      if (dayPlan.meals.dinner) {
        plannedMeals.push(convertMiraMealToPlanned(
          mealPlan.id,
          dateStr,
          'dinner',
          dayPlan.meals.dinner
        ));
      }

      // Add snacks
      if (dayPlan.meals.snacks) {
        plannedMeals.push(convertMiraMealToPlanned(
          mealPlan.id,
          dateStr,
          'snack',
          dayPlan.meals.snacks
        ));
      }
    }

    // Insert all planned meals
    if (plannedMeals.length > 0) {
      const { data: meals, error: mealsError } = await supabase
        .from('planned_meals')
        .insert(plannedMeals)
        .select();

      if (mealsError) {
        logger.error('Failed to create planned meals:', mealsError);
        // Delete the meal plan since we couldn't add meals
        await supabase.from('meal_plans').delete().eq('id', mealPlan.id);
        throw mealsError;
      }

      return {
        ...mealPlan,
        planned_meals: meals || [],
      };
    }

    return {
      ...mealPlan,
      planned_meals: [],
    };
  } catch (error) {
    logger.error('saveMiraMealPlan error:', error);
    throw error;
  }
}

// Helper to convert Mira meal format to database format
function convertMiraMealToPlanned(
  mealPlanId: string,
  date: string,
  mealType: PlannedMeal['meal_type'],
  miraMeal: MiraMeal
): Omit<PlannedMeal, 'id' | 'created_at'> {
  return {
    meal_plan_id: mealPlanId,
    date,
    meal_type: mealType,
    name: miraMeal.name,
    description: miraMeal.description || null,
    calories: miraMeal.calories || null,
    prep_time: miraMeal.prepTime || null,
    ingredients: miraMeal.ingredients || [],
    instructions: [],
    is_completed: false,
    completed_at: null,
  };
}

// Add a single meal to a plan
export async function addMealToPlan(
  planId: string,
  date: string,
  meal: {
    meal_type: PlannedMeal['meal_type'];
    name: string;
    description?: string;
    calories?: number;
    prep_time?: string;
    ingredients?: string[];
    instructions?: string[];
  }
): Promise<PlannedMeal> {
  try {
    const { data, error } = await supabase
      .from('planned_meals')
      .insert({
        meal_plan_id: planId,
        date,
        meal_type: meal.meal_type,
        name: meal.name,
        description: meal.description || null,
        calories: meal.calories || null,
        prep_time: meal.prep_time || null,
        ingredients: meal.ingredients || [],
        instructions: meal.instructions || [],
        is_completed: false,
      })
      .select()
      .single();

    if (error) {
      logger.error('Failed to add meal:', error);
      throw error;
    }

    return data;
  } catch (error) {
    logger.error('addMealToPlan error:', error);
    throw error;
  }
}

// Create an empty meal plan (for manual entry)
export async function createEmptyMealPlan(
  householdId: string,
  name: string,
  startDate: Date,
  endDate: Date,
  userId?: string
): Promise<MealPlan> {
  try {
    const { data, error } = await supabase
      .from('meal_plans')
      .insert({
        household_id: householdId,
        name,
        start_date: startDate.toISOString().split('T')[0],
        end_date: endDate.toISOString().split('T')[0],
        created_by: userId || null,
      })
      .select()
      .single();

    if (error) {
      logger.error('Failed to create meal plan:', error);
      throw error;
    }

    return data;
  } catch (error) {
    logger.error('createEmptyMealPlan error:', error);
    throw error;
  }
}

// Update a meal
export async function updateMeal(
  mealId: string,
  updates: Partial<Pick<PlannedMeal, 'name' | 'description' | 'calories' | 'prep_time' | 'ingredients' | 'instructions' | 'is_completed'>>
): Promise<PlannedMeal> {
  try {
    const updateData: Record<string, any> = { ...updates };

    // Add completed_at timestamp if marking as completed
    if (updates.is_completed === true) {
      updateData.completed_at = new Date().toISOString();
    } else if (updates.is_completed === false) {
      updateData.completed_at = null;
    }

    const { data, error } = await supabase
      .from('planned_meals')
      .update(updateData)
      .eq('id', mealId)
      .select()
      .single();

    if (error) {
      logger.error('Failed to update meal:', error);
      throw error;
    }

    return data;
  } catch (error) {
    logger.error('updateMeal error:', error);
    throw error;
  }
}

// Delete a meal
export async function deleteMeal(mealId: string): Promise<void> {
  try {
    const { error } = await supabase
      .from('planned_meals')
      .delete()
      .eq('id', mealId);

    if (error) {
      logger.error('Failed to delete meal:', error);
      throw error;
    }
  } catch (error) {
    logger.error('deleteMeal error:', error);
    throw error;
  }
}

// Delete a meal plan and all its meals
export async function deleteMealPlan(planId: string): Promise<void> {
  try {
    // Meals will be deleted automatically via CASCADE
    const { error } = await supabase
      .from('meal_plans')
      .delete()
      .eq('id', planId);

    if (error) {
      logger.error('Failed to delete meal plan:', error);
      throw error;
    }
  } catch (error) {
    logger.error('deleteMealPlan error:', error);
    throw error;
  }
}

// Get the current/active meal plan (most recent that includes today)
export async function getCurrentMealPlan(householdId: string): Promise<MealPlanWithMeals | null> {
  try {
    const today = new Date().toISOString().split('T')[0];

    const { data, error } = await supabase
      .from('meal_plans')
      .select(`
        *,
        planned_meals (*)
      `)
      .eq('household_id', householdId)
      .lte('start_date', today)
      .gte('end_date', today)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null; // Not found
      logger.error('Failed to fetch current meal plan:', error);
      throw error;
    }

    return data;
  } catch (error) {
    logger.error('getCurrentMealPlan error:', error);
    return null;
  }
}
