-- REMOVED: Client-side subscription writes are no longer used.
-- Subscriptions are now activated via the apple-verify-receipt Edge Function
-- using service_role, which is more secure.
-- Original policies removed by 20260223_remove_client_subscription_writes.sql
